### ISSUE TITLE
No bucket return on craft

### ISSUE THREAD

**Issue by arcadetoaster** [pnk2u/Bake-Your-Bread#1] opened 2024-11-28 05:19 UTC
Upon crafting all of the raw recipes in the mod, none of them return the bucket like the vanilla cake recipe and other modded recipes. It seems rather excessive that for one piece of bread I have to give up 3 iron ingots.

**Comment by pnk2u** [comment] 2024-11-28 05:48
Absolutely, that is not intended behavior, what minecraft version is this on? And just to confirm, you are using Fabric, right?

**Comment by arcadetoaster** [comment] 2024-11-28 06:11
Minecraft 1.21.1
Fabric 0.16.9
Bake Your Bread 1.1.0
I have a lot of other mods and just did some testing. Looks like the incompatibility is with Better than Wolves Remastered. I'll talk with the author.

**Comment by pnk2u** [comment] 2024-11-28 06:40
Alright, thanks for checking and letting me know. I will close this issue for now then, feel free to re-open it, should my help be required for this. (:

**Closed as completed by pnk2u** 2024-11-28 06:40 UTC
